name: Build Docker Image

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate common locale
        run: pnpm docs:gen-locale

      - name: Install latest Element Plus
        run: cd docs && pnpm i element-plus@latest

      - name: Build Metadata
        run: cd internal/metadata && pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website
        run: pnpm docs:build
        env:
          DOC_ENV: production

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xbeeant/element3
          tags: latest
